name: Update Wiki
on:
  push # gollum
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the wiki repository
  #       uses: actions/checkout@v2
  #       with:
  #         repository: "${{ github.repository }}.wiki"
  #         ref: master
  #         path: .wiki

  #     - name: Generate the Wiki Page
  #     - uses: actions/setup-node@v2
  #       run: |
  #         set -xe
  #         echo `date +'%Y-%m-%dT%H-%M'` | tee .wiki/Test.md
  #       env:
  #         TZ: Asia/Tokyo

  #     - name: Configure the GitHub wiki identity
  #       working-directory: .wiki
  #       run: |
  #         set -xe
  #         git config user.name  "[bot] ${GITHUB_ACTOR}"
  #         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

  #     - name: Update the wiki page
  #       working-directory: .wiki
  #       run: |
  #         set -xe
  #         git add .
  #         git commit --allow-empty -m "update the wiki page by bot (${GITHUB_WORKFLOW})"
  #         git push origin master

  # notify:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Discord
  #       run: |
  #         curl -X POST -H 'Content-type: application/json' \
  #           --data "{\"content\": \"Repo ${{github.repository}}\"}" \
  #           ${{secrets.WEBHOOK_URL}}

  debug:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Discord
        run: |
          echo '${{ toJSON(github) }}'
          echo '${{ toJSON(job) }}'
          echo '${{ toJSON(steps) }}'
          echo '${{ toJSON(runner) }}'
          echo '${{ toJSON(env) }}'
          echo '${{ toJSON(secrets) }}'
        env:
          TZ: Asia/Tokyo

      - name: Extract all keywords from package.json
        uses: sergeysova/jq-action@v2
        id: keywords
        with:
          cmd: 'jq .keywords[] package.json -r'
          multiline: true
