name: Wiki
on:
  gollum
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the wiki repository
        uses: actions/checkout@v2
        with:
          repository: "${{ github.repository }}.wiki"
          ref: master
          path: .wiki

      - uses: actions/setup-node@v2
      - name: Generate the Wiki Page
        run: |
          set -xe
          echo `date +'%y.%m.%d %H:%M'` | tee .wiki/Test.md


      - name: Configure the GitHub wiki identity
        working-directory: .wiki
        run: |
          set -xe
          git config user.name  "[bot] ${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Update the wiki page
        working-directory: .wiki
        run: |
          set -xe
          git add .
          git commit --allow-empty -m "update the wiki page by bot (${GITHUB_WORKFLOW})"
          git push origin master
